export const ETFdata = {
  title: "Copper ETF Holdings (Million lbs)",
  regions: [
    {
      name: "North America",
      funds: [
        {
          fund: "Global X Copper Miners ETF",
          country: "US",
          inception: "25/04/2012",
          ticker: "COPX US Equity",
          managementFee: 0.65,
          currentOz: 850000,
          valueUSD: 425,
          percentTotal: 35,
          symbol: "NASDAQ:COPX",
        },
        {
          fund: "iPath Series B Bloomberg Copper ETN",
          country: "US",
          inception: "23/10/2018",
          ticker: "JJC US Equity",
          managementFee: 0.45,
          currentOz: 320000,
          valueUSD: 160,
          percentTotal: 15,
          symbol: "NASDAQ:JJC",
        },
        {
          fund: "United States Copper Index Fund",
          country: "US",
          inception: "15/11/2011",
          ticker: "CPER US Equity",
          managementFee: 0.95,
          currentOz: 180000,
          valueUSD: 90,
          percentTotal: 8,
          symbol: "NASDAQ:CPER",
        },
        {
          fund: "Invesco DB Base Metals Fund",
          country: "US",
          inception: "06/01/2007",
          ticker: "DBB US Equity",
          managementFee: 0.75,
          currentOz: 240000,
          valueUSD: 120,
          percentTotal: 10,
          symbol: "NASDAQ:DBB",
        },
      ],
      totals: {
        currentOz: 1590000,
        valueUSD: 795,
        percentTotal: 68,
      },
    },

    {
      name: "Europe",
      _funds: [
        {
          fund: "WisdomTree Copper",
          country: "GB",
          inception: "15/12/2006",
          ticker: "COPA LN Equity",
          managementFee: 0.49,
          currentOz: 120000,
          valueUSD: 60,
          percentTotal: 5,
          symbol: "LSE:COPA",
        },
        {
          fund: "Xtrackers MSCI World Materials UCITS ETF",
          country: "DE",
          inception: "19/12/2014",
          ticker: "XMAW GR Equity",
          managementFee: 0.25,
          currentOz: 95000,
          valueUSD: 48,
          percentTotal: 4,
          symbol: "XETRA:XMAW",
        },
        {
          fund: "iShares MSCI World Materials Sector ESG UCITS ETF",
          country: "IE",
          inception: "28/09/2018",
          ticker: "WMAT LN Equity",
          managementFee: 0.25,
          currentOz: 75000,
          valueUSD: 38,
          percentTotal: 3,
          symbol: "LSE:WMAT",
        },
        {
          fund: "SPDR S&P Metals & Mining ETF",
          country: "US",
          inception: "28/10/2006",
          ticker: "XME US Equity",
          managementFee: 0.35,
          currentOz: 110000,
          valueUSD: 55,
          percentTotal: 5,
          symbol: "NASDAQ:XME",
        },
      ],
      get funds() {
        return this._funds;
      },
      set funds(value) {
        this._funds = value;
      },
      totals: {
        currentOz: 400000,
        valueUSD: 201,
        percentTotal: 17,
      },
    },
    {
      name: "South Africa",
      funds: [
        {
          fund: "Satrix MSCI World Materials ETF",
          country: "ZA",
          inception: "15/03/2019",
          ticker: "STXWDM SJ Equity",
          managementFee: 0.40,
          currentOz: 85000,
          valueUSD: 43,
          percentTotal: 4,
          symbol: "JSE:STXWDM",
        },
        {
          fund: "CoreShares S&P Global Base Metals ETF",
          country: "ZA",
          inception: "12/11/2018",
          ticker: "GLBMET SJ Equity",
          managementFee: 0.65,
          currentOz: 65000,
          valueUSD: 33,
          percentTotal: 3,
          symbol: "JSE:GLBMET",
        },
      ],
      totals: {
        currentOz: 150000,
        valueUSD: 76,
        percentTotal: 7,
      },
    },
    {
      name: "Asia",
      funds: [
        {
          fund: "ETFS Physical Copper",
          country: "AU",
          inception: "10/04/2020",
          ticker: "ETPMCU AU Equity",
          managementFee: 0.49,
          currentOz: 95000,
          valueUSD: 48,
          percentTotal: 4,
          symbol: "ASX:ETPMCU",
        },
        {
          fund: "BetaShares Global Base Metals ETF - Currency Hedged",
          country: "AU",
          inception: "13/08/2018",
          ticker: "MNRS AU Equity",
          managementFee: 0.57,
          currentOz: 75000,
          valueUSD: 38,
          percentTotal: 3,
          symbol: "ASX:MNRS",
        },
        {
          fund: "Xtrackers MSCI World Materials UCITS ETF",
          country: "HK",
          inception: "15/11/2017",
          ticker: "3120 HK Equity",
          managementFee: 0.25,
          currentOz: 55000,
          valueUSD: 28,
          percentTotal: 2,
          symbol: "HKEX:3120",
        },
      ],
      totals: {
        currentOz: 225000,
        valueUSD: 114,
        percentTotal: 9,
      },
    },
  ],
  grandTotal: {
    currentOz: 2365000,
    valueUSD: 1186,
    percentTotal: 100,
  },
  metadata: {
    source: "Bloomberg, Respective ETF providers, Copper Market Research",
    lastUpdate: "30-November-2024",
  },
};
