export const ETFdata = {
  title: "Copper ETF Holdings (Million lbs)",
  regions: [
    {
      name: "North America",
      funds: [
        {
          fund: "Apple Inc",
          country: "US",
          inception: "25/04/2012",
          ticker: "AAPL US Equity",
          managementFee: 0.00,
          currentOz: 850000,
          valueUSD: 425,
          percentTotal: 35,
          symbol: "NASDAQ:AAPL",
        },
        {
          fund: "Microsoft Corporation",
          country: "US",
          inception: "23/10/2018",
          ticker: "MSFT US Equity",
          managementFee: 0.00,
          currentOz: 320000,
          valueUSD: 160,
          percentTotal: 15,
          symbol: "NASDAQ:MSFT",
        },
        {
          fund: "Alphabet Inc",
          country: "US",
          inception: "15/11/2011",
          ticker: "GOOGL US Equity",
          managementFee: 0.00,
          currentOz: 180000,
          valueUSD: 90,
          percentTotal: 8,
          symbol: "NASDAQ:GOOGL",
        },
        {
          fund: "Amazon.com Inc",
          country: "US",
          inception: "06/01/2007",
          ticker: "AMZN US Equity",
          managementFee: 0.00,
          currentOz: 240000,
          valueUSD: 120,
          percentTotal: 10,
          symbol: "NASDAQ:AMZN",
        },
      ],
      totals: {
        currentOz: 1590000,
        valueUSD: 795,
        percentTotal: 68,
      },
    },

    {
      name: "Europe",
      _funds: [
        {
          fund: "Tesla Inc",
          country: "US",
          inception: "15/12/2006",
          ticker: "TSLA US Equity",
          managementFee: 0.00,
          currentOz: 120000,
          valueUSD: 60,
          percentTotal: 5,
          symbol: "NASDAQ:TSLA",
        },
        {
          fund: "Meta Platforms Inc",
          country: "US",
          inception: "19/12/2014",
          ticker: "META US Equity",
          managementFee: 0.00,
          currentOz: 95000,
          valueUSD: 48,
          percentTotal: 4,
          symbol: "NASDAQ:META",
        },
        {
          fund: "NVIDIA Corporation",
          country: "US",
          inception: "28/09/2018",
          ticker: "NVDA US Equity",
          managementFee: 0.00,
          currentOz: 75000,
          valueUSD: 38,
          percentTotal: 3,
          symbol: "NASDAQ:NVDA",
        },
        {
          fund: "Netflix Inc",
          country: "US",
          inception: "28/10/2006",
          ticker: "NFLX US Equity",
          managementFee: 0.00,
          currentOz: 110000,
          valueUSD: 55,
          percentTotal: 5,
          symbol: "NASDAQ:NFLX",
        },
      ],
      get funds() {
        return this._funds;
      },
      set funds(value) {
        this._funds = value;
      },
      totals: {
        currentOz: 400000,
        valueUSD: 201,
        percentTotal: 17,
      },
    },
    {
      name: "South Africa",
      funds: [
        {
          fund: "JPMorgan Chase & Co",
          country: "US",
          inception: "15/03/2019",
          ticker: "JPM US Equity",
          managementFee: 0.00,
          currentOz: 85000,
          valueUSD: 43,
          percentTotal: 4,
          symbol: "NYSE:JPM",
        },
        {
          fund: "Johnson & Johnson",
          country: "US",
          inception: "12/11/2018",
          ticker: "JNJ US Equity",
          managementFee: 0.00,
          currentOz: 65000,
          valueUSD: 33,
          percentTotal: 3,
          symbol: "NYSE:JNJ",
        },
      ],
      totals: {
        currentOz: 150000,
        valueUSD: 76,
        percentTotal: 7,
      },
    },
    {
      name: "Asia",
      funds: [
        {
          fund: "Visa Inc",
          country: "US",
          inception: "10/04/2020",
          ticker: "V US Equity",
          managementFee: 0.00,
          currentOz: 95000,
          valueUSD: 48,
          percentTotal: 4,
          symbol: "NYSE:V",
        },
        {
          fund: "Procter & Gamble Co",
          country: "US",
          inception: "13/08/2018",
          ticker: "PG US Equity",
          managementFee: 0.00,
          currentOz: 75000,
          valueUSD: 38,
          percentTotal: 3,
          symbol: "NYSE:PG",
        },
        {
          fund: "Walmart Inc",
          country: "US",
          inception: "15/11/2017",
          ticker: "WMT US Equity",
          managementFee: 0.00,
          currentOz: 55000,
          valueUSD: 28,
          percentTotal: 2,
          symbol: "NYSE:WMT",
        },
      ],
      totals: {
        currentOz: 225000,
        valueUSD: 114,
        percentTotal: 9,
      },
    },
  ],
  grandTotal: {
    currentOz: 2365000,
    valueUSD: 1186,
    percentTotal: 100,
  },
  metadata: {
    source: "Bloomberg, Respective ETF providers, Copper Market Research",
    lastUpdate: "30-November-2024",
  },
};
