export const ETFdata = {
  title: "ETP holdings (koz)",
  regions: [
    {
      name: "North America",
      funds: [
        {
          fund: "abrdn Physical Precious Metals Basket Shares ETF",
          country: "US",
          inception: "22/10/2010",
          ticker: "GLTR US Equity",
          managementFee: 0.6,
          currentOz: 34932,
          valueUSD: 33,
          percentTotal: 1,
          symbol: "AMEX:GLTR",
        },
        {
          fund: "abrdn Physical Platinum Shares ETF",
          country: "US",
          inception: "08/01/2010",
          ticker: "PPLT US Equity",
          managementFee: 0.6,
          currentOz: 1133013,
          valueUSD: 1064,
          percentTotal: 34,
          symbol: "AMEX:PPLT",
        },
        {
          fund: "Sprott Physical Platinum & Palladium Trust",
          country: "US",
          inception: "19/12/2012",
          ticker: "SPPP US Equity",
          managementFee: 0.5,
          currentOz: 93738,
          valueUSD: 88,
          percentTotal: 3,
          symbol: "AMEX:SPPP",
        },
        {
          fund: "GraniteShares Platinum Trust",
          country: "US",
          inception: "22/01/2018",
          ticker: "PLTM US Equity",
          managementFee: 0.5,
          currentOz: 45434,
          valueUSD: 43,
          percentTotal: 1,
          symbol: "AMEX:PLTM",
        },
      ],
      totals: {
        currentOz: 1307117,
        valueUSD: 1227,
        percentTotal: 40,
      },
    },

    {
      name: "Europe",
      _funds: [
        {
          fund: "Xtrackers Physical Platinum EUR Hedged ETC",
          country: "DE",
          inception: "26/07/2010",
          ticker: "XAD3 GR Equity",
          managementFee: 0.75,
          currentOz: 60128,
          valueUSD: 56,
          percentTotal: 2,
          symbol: "MIL:XAD3",
        },
        {
          fund: "Xtrackers IE Physical Platinum EUR Hedged ETC Securities",
          country: "DE",
          inception: "02/06/2020",
          ticker: "XPPE GR Equity",
          managementFee: 0.73,
          currentOz: 8215,
          valueUSD: 8,
          percentTotal: 0,
          symbol: "MIL:XPPE",
        },

        {
          fund: "UBS ETF CH-Platinum",
          country: "CH",
          inception: "10/09/2010",
          ticker: "PTCHA SW Equity",
          managementFee: 0.35,
          currentOz: 49006,
          valueUSD: 46,
          percentTotal: 1,
          symbol: "TURQUOISE:PTCHAZ",
        },
        {
          fund: "ZKB Platinum ETF",
          country: "CH",
          inception: "10/05/2007",
          ticker: "ZPLA SW Equity",
          managementFee: 0.5,
          currentOz: 457042,
          valueUSD: 429,
          percentTotal: 14,
          symbol: "SIX:ZPLA",
        },
      ],
      get funds() {
        return this._funds;
      },
      set funds(value) {
        this._funds = value;
      },
      totals: {
        currentOz: 1348957,
        valueUSD: 1267,
        percentTotal: 41,
      },
    },
    {
      name: "South Africa",
      funds: [
        {
          fund: "1nvest Platinum ETF",
          country: "ZA",
          inception: "07/04/2014",
          ticker: "ETFPLT SJ Equity",
          managementFee: 0.3,
          currentOz: 119593,
          valueUSD: 112,
          percentTotal: 4,
          symbol: "JSE:ETFPLT",
        },
        {
          fund: "New Gold Platinum ETF",
          country: "ZA",
          inception: "26/04/2013",
          ticker: "NGPLT SJ Equity",
          managementFee: 0.35,
          currentOz: 404698,
          valueUSD: 380,
          percentTotal: 12,
          symbol: "JSE:NGPLT",
        },
      ],
      totals: {
        currentOz: 524291,
        valueUSD: 492,
        percentTotal: 16,
      },
    },
    {
      name: "Asia",
      funds: [
        {
          fund: "Global X Physical Platinum",
          country: "AU",
          inception: "30/01/2009",
          ticker: "ETPMPT AU Equity",
          managementFee: 0.49,
          currentOz: 16963,
          valueUSD: 16,
          percentTotal: 1,
          symbol: "ASX:ETPMPT",
        },
      ],
      totals: {
        currentOz: 116511,
        valueUSD: 109,
        percentTotal: 4,
      },
    },
  ],
  grandTotal: {
    currentOz: 3296877,
    valueUSD: 3096,
    percentTotal: 100,
  },
  metadata: {
    source: "Bloomberg, Respective ETP providers, WPIC research",
    lastUpdate: "30-November-2024",
  },
};
